fichier:
    resource: "@FichierBundle/Controller/"
    type:     annotation
    prefix:   /dossier

annuaire:
    resource: "@AnnuaireBundle/Controller/"
    type:     annotation
    prefix:   /annuaire

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

stats:
    resource: "@StatsBundle/Controller/"
    type:     annotation
    prefix:   /stats

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /forum

formation:
    resource: "@FormationBundle/Controller/"
    type:     annotation
    prefix:   /formation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"